# STAGE 1: MÔI TRƯỜNG BIÊN DỊCH (Build)
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Tối ưu Cache: Copy file csproj vào trước để restore
COPY ["GymBro.Product.API.csproj", "./"]
RUN dotnet restore "./GymBro.Product.API.csproj"

# Copy toàn bộ mã nguồn còn lại và Build
COPY . .
RUN dotnet build "GymBro.Product.API.csproj" -c Release -o /app/build
RUN dotnet publish "GymBro.Product.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

# STAGE 2: MÔI TRƯỜNG THỰC THI (Runtime)
# Chỉ sử dụng image aspnet cực nhẹ, loại bỏ hoàn toàn SDK và Source code
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
EXPOSE 8080

# Chỉ copy thành phẩm (.dll) từ STAGE 1 sang STAGE 2
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "GymBro.Product.API.dll"]