<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.68.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GymBro.Infrastructure\GymBro.Infrastructure.csproj" />
    <ProjectReference Include="..\GymBro.Core\GymBro.Core.csproj" />
    <ProjectReference Include="..\GymBro.Contracts\GymBro.Contracts.csproj" />
    <ProjectReference Include="..\GymBro.Order.API\GymBro.Order.API.csproj" />
    <ProjectReference Include="..\GymBro.Product.API\GymBro.Product.API.csproj" />
    <ProjectReference Include="..\GymBro.Service\GymBro.Service.csproj" />
    <ProjectReference Include="..\GymBro.Web\GymBro.Web.csproj" />
  </ItemGroup>

</Project>
