# Baseline Single-stage (THUẦN TÚY) — SDK image cho cả build và runtime
FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /src

COPY . .
WORKDIR /src/GymBro.Order.API

RUN dotnet restore "GymBro.Order.API.csproj"
RUN dotnet publish "GymBro.Order.API.csproj" -c Release -o /app/publish /p:UseAppHost=false /p:ErrorOnDuplicatePublishOutputFiles=false

WORKDIR /app/publish
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "GymBro.Order.API.dll"]